### ISSUE TITLE
transfer closed with xxx bytes remaining to read

### ISSUE THREAD

**Issue by developer4ATIT** [osoobe/dubizzle-php#2]
transfer closed with xxx bytes remaining to read

Most of the time i get this error is there something wrong with your code.

**Comment by b4oshany** [comment]
Can you send me a screenshot or snippet of the error? Nevertheless, `transfer closed with xxx bytes remaining to read` is a curl error. I don't think anything is wrong with the code. It's working locally and on the development server I setup.

**Comment by b4oshany** [comment]
I made a tweak to the code. Update the package using composer update.

**Comment by developer4ATIT** [comment]
Thank you.. 

I have another issue if you can figure out. The result count on dubizzle and by fetching our API is different. 

For Example:
https://dubai.dubizzle.com/motors/used-cars/audi/a4/?year__gte=2005&year__lte=2005&body_type=348

IF you check the above link you will see around 5 records but when we fetch via our code below we get 2-3 records why is it not fetching the complete list. can you make an example for this Make/Model/Year/Type. 

$params = array(
  "country" => 'all', 
  "city" => 'all',
  "section" => 'motors',
  "category" => 'cars',
  "make" => 'audi',
  "model" => '1187', //A4
  "body_type"=>'348', //Sedan
  "min_year" => '2005',
  "max_year" => '2005',
  "num_results" => 'all');

   $uae_dubizzle = new Search($params);
   //Rest you know the code

Help would be appreciated.

**Comment by b4oshany** [comment]
I will update the code shortly. Apparently, the reason why you are seeing 3 results instead of 5 is because of the ads posted param is set to within a month instead of any time.
![dubizzle dubai - motors and cars classifieds in dubai uae 2015-11-03 10-30-20](https://cloud.githubusercontent.com/assets/1830494/10912649/6cf2aa88-8218-11e5-95d5-330954c4912e.png)

In addition, you can use `$uae_dubizzle->query_url()` to get the exact url to visit and see the results via browser.

**Comment by b4oshany** [comment]
If you put `'added_days' => ''`, it should work. I checked the code and realized that `added_days` is set to 30. As a result, only ads that were post within 30 days will be showed. I'm going to set the default to "", which means any time.

**Comment by developer4ATIT** [comment]
Thanks for the update.

But still facing an issue. 

Check this link from dubizzle
https://uae.dubizzle.com/motors/used-cars/chevrolet/corvette/?site=--&s=MT&rc=140&c1=1235&c2=1239&price__gte=&price__lte=&year__gte=2011&year__lte=2011&kilometers__gte=&kilometers__lte=&seller_type=&keywords=&is_basic_search_widget=0&is_search=1&added__gte=&auto_agent=&body_type=347

Above dubizzle show 1 record and our compiler zero.. Is it that if you get more than one record then only compiler works? Please help me have tested i am not getting singular records only

My code to fetch

$params = array(
"country" => 'uae',
"city" => 'all',
"section" => 'motors',
"category" => 'cars',
"make" => 'chevrolet',
"model" => '1239',  //Corvette
"body_type"=>'347',  //Coupe
"min_year" => '2011',
"max_year" => '2011',
"num_results" => '100',
"added_days"=>'');
$uae_dubizzle = new Search($params);

**Comment by b4oshany** [comment]
Apparently, dubizzle had a featured item tag that wasn't captured by the api. I added the capturing of featured items.
