### ISSUE TITLE
Can you please send me the zip folder..

### ISSUE THREAD

**Issue by developer4ATIT** [osoobe/dubizzle-php#3]
Can you please send me the zip folder there is some issue with vendor folder.. This is last and final request bro. Thanks in advance.

**Comment by b4oshany** [comment]
if you run: `composer update` it should fix the vendor package. Anyhow, here is the link for the zip file: http://osoobe.com/downloads/dubizzle-php.zip

**Comment by b4oshany** [comment]
Oh... and I don't mind since the more problems you find is the better for everyone.

**Comment by developer4ATIT** [comment]
Ok, Thanks.  But there is one more i am getting first page record how can i get all the pages records 
for example is the record count in dubizzle is 70 its shows 25(first page records).. Is there a way to get all?

**Comment by b4oshany** [comment]
Yes, there is. The Search class takes two params, `args` and `num_results`. If you set `num_results` to 70, you'll get that amount:

``` php
$uae = new Search($param, 70);
```

https://github.com/osoobe/dubizzle-php/blob/master/src/Dubizzle/Search.php#L14
