### ISSUE TITLE
Please come on SkyPe 

### ISSUE THREAD

**Issue by developer4ATIT** [osoobe/dubizzle-php#5]
Just Fix the code for getting all the pages currently it gets only 25. Why are you not responding.

**Comment by b4oshany** [comment]
Hi,

Sorry for my MIA (Missing in Action) status. My system is down. There was a
power surge a couple of days ago and my system got affected by it. I'm
currently, using a friend system. The code is online.

PHPMyAdmin:
http://osoobe.com/phpmyadmin/
username: dubizzle
pass: dubtest

url for updating make:
http://osoobe.com/dubizzle-cron/dubizzle_cron.php?do=update_makes

url for updating models:
http://osoobe.com/dubizzle-cron/dubizzle_cron.php?do=update_models

url for model results:
http://osoobe.com/dubizzle-cron/dubizzle_cron.php?do=make_model_result


See attachment for code and sql

For cronjobs:
https://www.setcronjob.com/

I'll contact you later when I get a next computer. I'm very sorry for the
inconvenience my current situation as cost you, and yes, you may deduct $10
when we've completed the task at hand.

On Thu, Nov 19, 2015 at 10:20 AM, Developer ATIT <notifications@github.com>
wrote:

> Just Fix the code for getting all the pages currently it gets only 25. Why
> are you not responding.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osoobe/dubizzle-php/issues/5>.
>



-- 
O. Bailey
